export type ThemeColors = {
  id: string;
  name: string;
  description: string;
  colors: {
    light: Record<string, string>;
    dark: Record<string, string>;
  };
};

export const themes: ThemeColors[] = [
  {
    id: "mor",
    name: "mor",
    description: "varsayılan kuzu sözlük teması",
    colors: {
      light: {
        "--primary": "#9333ea",
        "--primary-foreground": "#ffffff",
        "--accent": "#faf5ff",
        "--ring": "#9333ea",
        "--border": "#e9e5f0",
        "--muted": "#f5f3f8",
        "--muted-foreground": "#6b6080",
      },
      dark: {
        "--primary": "#a78bfa",
        "--primary-foreground": "#0f0f12",
        "--accent": "#2d2a35",
        "--ring": "#a78bfa",
        "--border": "#3a3545",
        "--muted": "#2a2730",
        "--muted-foreground": "#9590a0",
      },
    },
  },
  {
    id: "mavi",
    name: "okyanus",
    description: "klasik mavi tonlar",
    colors: {
      light: {
        "--primary": "#2563eb",
        "--primary-foreground": "#ffffff",
        "--accent": "#eff6ff",
        "--ring": "#2563eb",
        "--border": "#d0dff0",
        "--muted": "#f0f5fc",
        "--muted-foreground": "#5070a0",
      },
      dark: {
        "--primary": "#60a5fa",
        "--primary-foreground": "#0a0a12",
        "--accent": "#1a2540",
        "--ring": "#60a5fa",
        "--border": "#2a3550",
        "--muted": "#1a2035",
        "--muted-foreground": "#7090b5",
      },
    },
  },
  {
    id: "yesil",
    name: "orman",
    description: "doğal yeşil tonlar",
    colors: {
      light: {
        "--primary": "#16a34a",
        "--primary-foreground": "#ffffff",
        "--accent": "#f0fdf4",
        "--ring": "#16a34a",
        "--border": "#d0e8d8",
        "--muted": "#f0f8f2",
        "--muted-foreground": "#508060",
      },
      dark: {
        "--primary": "#4ade80",
        "--primary-foreground": "#0a0f0a",
        "--accent": "#1a2e1a",
        "--ring": "#4ade80",
        "--border": "#2a3a2a",
        "--muted": "#1a251a",
        "--muted-foreground": "#70a080",
      },
    },
  },
  {
    id: "pembe",
    name: "pembe",
    description: "yumuşak pembe tonları",
    colors: {
      light: {
        "--primary": "#ec4899",
        "--primary-foreground": "#ffffff",
        "--accent": "#fdf2f8",
        "--ring": "#ec4899",
        "--border": "#f0d5e5",
        "--muted": "#fdf5fa",
        "--muted-foreground": "#a06080",
      },
      dark: {
        "--primary": "#f472b6",
        "--primary-foreground": "#0f0a0d",
        "--accent": "#352a30",
        "--ring": "#f472b6",
        "--border": "#452535",
        "--muted": "#2a1a25",
        "--muted-foreground": "#b07090",
      },
    },
  },
  {
    id: "lavanta",
    name: "lavanta",
    description: "huzur veren lavanta",
    colors: {
      light: {
        "--primary": "#8b5cf6",
        "--primary-foreground": "#ffffff",
        "--accent": "#f5f3ff",
        "--ring": "#8b5cf6",
        "--border": "#e0d8f0",
        "--muted": "#f5f0ff",
        "--muted-foreground": "#7060a0",
      },
      dark: {
        "--primary": "#c4b5fd",
        "--primary-foreground": "#0f0d15",
        "--accent": "#2e2a3a",
        "--ring": "#c4b5fd",
        "--border": "#3a3050",
        "--muted": "#252030",
        "--muted-foreground": "#9585b5",
      },
    },
  },
  {
    id: "celik",
    name: "çelik",
    description: "minimal gri tonları",
    colors: {
      light: {
        "--primary": "#475569",
        "--primary-foreground": "#ffffff",
        "--accent": "#f1f5f9",
        "--ring": "#475569",
        "--border": "#d0d5dd",
        "--muted": "#f0f2f5",
        "--muted-foreground": "#606878",
      },
      dark: {
        "--primary": "#94a3b8",
        "--primary-foreground": "#0a0c10",
        "--accent": "#1e2535",
        "--ring": "#94a3b8",
        "--border": "#303848",
        "--muted": "#1a2030",
        "--muted-foreground": "#7585a0",
      },
    },
  },
  {
    id: "amber",
    name: "amber",
    description: "sıcak amber tonları",
    colors: {
      light: {
        "--primary": "#d97706",
        "--primary-foreground": "#ffffff",
        "--accent": "#fffbeb",
        "--ring": "#d97706",
        "--border": "#e8d8b8",
        "--muted": "#fdf8ee",
        "--muted-foreground": "#907040",
      },
      dark: {
        "--primary": "#fbbf24",
        "--primary-foreground": "#0f0d05",
        "--accent": "#352e1a",
        "--ring": "#fbbf24",
        "--border": "#403520",
        "--muted": "#2a2518",
        "--muted-foreground": "#b09060",
      },
    },
  },
  {
    id: "kirmizi",
    name: "ateş",
    description: "cesur kırmızı tonlar",
    colors: {
      light: {
        "--primary": "#dc2626",
        "--primary-foreground": "#ffffff",
        "--accent": "#fef2f2",
        "--ring": "#dc2626",
        "--border": "#f0d0d0",
        "--muted": "#fdf5f5",
        "--muted-foreground": "#a05050",
      },
      dark: {
        "--primary": "#f87171",
        "--primary-foreground": "#0f0a0a",
        "--accent": "#352020",
        "--ring": "#f87171",
        "--border": "#452525",
        "--muted": "#2a1a1a",
        "--muted-foreground": "#b06060",
      },
    },
  },
  {
    id: "turkuaz",
    name: "deniz",
    description: "ferah turkuaz tonlar",
    colors: {
      light: {
        "--primary": "#0891b2",
        "--primary-foreground": "#ffffff",
        "--accent": "#ecfeff",
        "--ring": "#0891b2",
        "--border": "#c0e0e8",
        "--muted": "#f0fafb",
        "--muted-foreground": "#407888",
      },
      dark: {
        "--primary": "#22d3ee",
        "--primary-foreground": "#0a0f10",
        "--accent": "#1a2e30",
        "--ring": "#22d3ee",
        "--border": "#253838",
        "--muted": "#1a2828",
        "--muted-foreground": "#60a0b0",
      },
    },
  },
  {
    id: "sozlukspot",
    name: "sözlükspot",
    description: "sözlükspot grisi, mavi vurgulu",
    colors: {
      light: {
        "--background": "#cdcccc",
        "--foreground": "#1a1a1a",
        "--card": "#d8d7d7",
        "--card-foreground": "#1a1a1a",
        "--popover": "#d8d7d7",
        "--popover-foreground": "#1a1a1a",
        "--primary": "#264d71",
        "--primary-foreground": "#ffffff",
        "--secondary": "#c0bfbf",
        "--secondary-foreground": "#1a1a1a",
        "--accent": "#c2c1c1",
        "--accent-foreground": "#1a1a1a",
        "--ring": "#264d71",
        "--border": "#b5b4b4",
        "--input": "#b5b4b4",
        "--muted": "#c2c1c1",
        "--muted-foreground": "#5a5a5a",
      },
      dark: {
        "--background": "#1a1a1e",
        "--foreground": "#d0d0d0",
        "--card": "#222226",
        "--card-foreground": "#d0d0d0",
        "--popover": "#222226",
        "--popover-foreground": "#d0d0d0",
        "--primary": "#5a9ac4",
        "--primary-foreground": "#0a0a12",
        "--secondary": "#2a2a2e",
        "--secondary-foreground": "#d0d0d0",
        "--accent": "#2a2a30",
        "--accent-foreground": "#d0d0d0",
        "--ring": "#5a9ac4",
        "--border": "#3a3a40",
        "--input": "#3a3a40",
        "--muted": "#2a2a2e",
        "--muted-foreground": "#808088",
      },
    },
  },
];

export function getThemeById(id: string) {
  return themes.find((t) => t.id === id) || themes[0];
}
